spring.application.name=sale-manager

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=no.reply.shahzad.sales.manager@gmail.com
spring.mail.password=xycnuewhdnbpuymv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true